package bhapps.menus.horizontal.horizontalmenu.helpers

object HorizontalMenuConfig {

    const val HORIZONTALMENU_BUILD_MENU_USING = "json"
    const val HORIZONTALMENU_BUILD_MENU_JSON_FILE = "bhapps_menus_horizontal_menu_config.json"

    //UI Settings
    const val HORIZONTALMENU_USESTYLESFROMTHEMES = true
    const val HORIZONTALMENU_WIDTH = 220f
    const val HORIZONTALMENU_SHOWACTIVESTATEONLEFT = false
    const val HORIZONTALMENU_SHOWPARENTICONS = true
    const val HORIZONTALMENU_SHOWPARENTDIVIDER = false
    const val HORIZONTALMENU_SHOWICONS = true
    const val HORIZONTALMENU_SHOWICONSONLY = false

    const val HORIZONTALMENU_COLLAPSETYPE = 1
    const val HORIZONTALMENU_COLLAPSEOTHERS = true
    const val HORIZONTALMENU_EXPANDCOLLAPSE_DELAY = 50
    const val HORIZONTALMENU_EXPANDCOLLAPSE_ROTATE = 180
    const val HORIZONTALMENU_ARROW_ROTATION_DURATION = 200

    const val HORIZONTALMENU_USEPREFERENCESETTINGS = true

    const val HORIZONTALMENU_PARENTITEMS_BADGE_DEFAULT_WIDTHHEIGHT_DP = 16
    const val HORIZONTALMENU_CHILDITEMS_BADGE_DEFAULT_WIDTHHEIGHT_DP = 16
}