package bhapps.menus.vertical.verticalmenu.helpers

object VerticalMenuConfig {

    const val VERTICALMENU_BUILD_MENU_USING = "json"
    const val VERTICALMENU_BUILD_MENU_JSON_FILE = "bhapps_menus_vertical_menu_config.json"

    //UI Settings
    const val VERTICALMENU_USESTYLESFROMTHEMES = true
    const val VERTICALMENU_WIDTH = 220f
    const val VERTICALMENU_SHOWACTIVESTATEONLEFT = false
    const val VERTICALMENU_SHOWPARENTICONS = true
    const val VERTICALMENU_SHOWPARENTDIVIDER = false
    const val VERTICALMENU_SHOWICONS = true
    const val VERTICALMENU_SHOWICONSONLY = false

    const val VERTICALMENU_COLLAPSETYPE = 1
    const val VERTICALMENU_COLLAPSEOTHERS = true
    const val VERTICALMENU_EXPANDCOLLAPSE_DELAY = 50
    const val VERTICALMENU_EXPANDCOLLAPSE_ROTATE = 180
    const val VERTICALMENU_ARROW_ROTATION_DURATION = 200

    const val VERTICALMENU_USEPREFERENCESETTINGS = true

    const val VERTICALMENU_PARENTITEMS_BADGE_DEFAULT_WIDTHHEIGHT_DP = 16
    const val VERTICALMENU_CHILDITEMS_BADGE_DEFAULT_WIDTHHEIGHT_DP = 16
}